In [140]:
import numpy as np

In [141]:
a=np.array([1,2,3,4])

In [142]:
print(a)

[1 2 3 4]


In [143]:
print(type(a))

<class 'numpy.ndarray'>


In [144]:
print(a.shape)

(4,)


In [145]:
b=np.array([[1],[2],[3],[4]])

In [146]:
print(b)

[[1]
 [2]
 [3]
 [4]]


In [147]:
print(b.shape)

(4, 1)


In [148]:
print(b[1][0])

2


In [149]:
c=np.array([[1,2,3],[4,5,6]])

In [150]:
print(c)

[[1 2 3]
 [4 5 6]]


In [151]:
print(c.shape)

(2, 3)


In [152]:
a=np.zeros((3,3))
b=np.ones((2,3))

In [153]:
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [154]:
c=np.full((3,2),5)

In [155]:
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [156]:
#identity matrix
d=np.eye(4)

In [157]:
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [158]:
#random matrix

In [159]:
randommatrix=np.random.random((2,3))

In [160]:
print(randommatrix)

[[0.04807384 0.65820799 0.94763042]
 [0.46334459 0.51305278 0.99012209]]


In [161]:
print(randommatrix[:,1])

[0.65820799 0.51305278]


In [162]:
randommatrix[1,1:]=1

In [163]:
print(randommatrix)

[[0.04807384 0.65820799 0.94763042]
 [0.46334459 1.         1.        ]]


In [164]:
# set some rows and columns with any values

In [165]:
z=np.zeros((3,3),dtype=np.int64)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [166]:
z[1,:]=5

In [167]:
z[:,-1]=7
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [168]:
#datatypes
print(z.dtype)

int64


In [169]:
#mathemtaical operations

In [170]:
x=np.array([[1,2],[3,4]])

In [171]:
y=np.array([[5,6],[7,8]])

In [172]:
print(x+y)
print(np.add(x,y))
print(x*y)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [173]:

print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [174]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [175]:
#matrix multiplication/dot product

In [176]:
print(x)

[[1 2]
 [3 4]]


In [177]:
print(y)

[[5 6]
 [7 8]]


In [178]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [179]:
#dot prudict of vectoers

In [180]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [181]:
print(sum(a))

10


In [182]:
print(np.sum(x,axis=0))

[4 6]


In [183]:
b=b**2
print(b)

[ 1  4  9 16]


In [184]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [185]:
a=np.stack((a,b),axis=0)

In [186]:
#reshape

In [187]:
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [188]:
a=a.reshape((4,2))

In [189]:
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [190]:
a=a.reshape((8,1))
# a.T

In [191]:
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [192]:
a=a.reshape((8,))

In [193]:
print(a)

[ 1  2  3  4  1  4  9 16]


In [194]:
q=np.arange(10)+5

In [195]:
print(q)

[ 5  6  7  8  9 10 11 12 13 14]


In [196]:
#random

In [197]:
np.random.shuffle(q)

In [198]:
print(q)

[10 11  5  8 14  7 13 12  6  9]


In [199]:
a=np.random.randint(5,10,3)

In [200]:
print(a)

[9 8 5]


In [201]:
#randompy pick element

In [202]:
element=np.random.choice([1,4,3,2,11])

In [203]:
print(element)

3


In [204]:
#numpy functions

In [205]:
print(min(q))

5


In [206]:
m=np.mean(q)

In [207]:
print(m)

9.5


In [208]:
print(np.median(q))

9.5


In [209]:
#standard deviation

In [210]:
u=np.mean(q)

In [211]:
mystd=np.sqrt(np.mean(abs(q-u)**2))

In [212]:
print(mystd)

2.8722813232690143


In [213]:
print(np.std(q))

2.8722813232690143


In [214]:
print(np.var(q))

8.25


In [228]:
w=np.array([
    [2,2],
    [3,4]
])

In [229]:
print(w)

[[2 2]
 [3 4]]


In [230]:
# w.T

In [231]:
x=np.array([4,4])

In [232]:
print(w+x)

[[6 6]
 [7 8]]
