In [13]:
import numpy as np
import pandas as pd
user_data={
    "marksa":np.random.randint(1,100,5),
    "marksb":np.random.randint(1,100,5),
    "marksc":np.random.randint(1,100,5),
}

In [14]:
np.random.randint(1,100,5)

array([33, 19, 22, 96,  6])

In [15]:
user_data

{'marksa': array([93, 12, 42,  4, 93]),
 'marksb': array([96, 91, 63, 25, 98]),
 'marksc': array([64, 14, 27, 93, 14])}

In [16]:
df=pd.DataFrame(user_data)

In [17]:
print(df)

   marksa  marksb  marksc
0      93      96      64
1      12      91      14
2      42      63      27
3       4      25      93
4      93      98      14


In [18]:
df.head()

marksa  marksb  marksc
0      93      96      64
1      12      91      14
2      42      63      27
3       4      25      93
4      93      98      14

In [19]:
df.head(n=3)

marksa  marksb  marksc
0      93      96      64
1      12      91      14
2      42      63      27

In [20]:
df.columns

Index(['marksa', 'marksb', 'marksc'], dtype='object')

In [23]:
df.to_csv("marks.csv")

In [24]:
my_data=pd.read_csv('marks.csv')

In [25]:
my_data

Unnamed: 0  marksa  marksb  marksc
0           0      93      96      64
1           1      12      91      14
2           2      42      63      27
3           3       4      25      93
4           4      93      98      14

In [32]:
my_data=pd.read_csv('marks.csv')
my_data=my_data.drop(columns=["Unnamed: 0"])

In [33]:
my_data

marksa  marksb  marksc
0      93      96      64
1      12      91      14
2      42      63      27
3       4      25      93
4      93      98      14

In [34]:
my_data.describe()

marksa     marksb     marksc
count   5.000000   5.000000   5.000000
mean   48.800000  74.600000  42.400000
std    42.763302  31.101447  34.918476
min     4.000000  25.000000  14.000000
25%    12.000000  63.000000  14.000000
50%    42.000000  91.000000  27.000000
75%    93.000000  96.000000  64.000000
max    93.000000  98.000000  93.000000

In [35]:
#for last 5 rows

In [36]:
my_data.tail()

marksa  marksb  marksc
0      93      96      64
1      12      91      14
2      42      63      27
3       4      25      93
4      93      98      14

In [38]:
df.iloc[3] #for accessing particulr row

marksa     4
marksb    25
marksc    93
Name: 3, dtype: int32

In [39]:
df.iloc[3,1]

25

In [40]:
df.iloc[3][1]

25

In [41]:
idx=df.columns.get_loc('marksb')

In [42]:
print(idx)

1


In [43]:
df.iloc[3,idx]

25

In [44]:
idx=[df.columns.get_loc('marksb'),df.columns.get_loc("marksc")] 

In [45]:
print(idx)

[1, 2]


In [46]:
df.iloc[3,idx]

marksb    25
marksc    93
Name: 3, dtype: int32

In [47]:
df.iloc[:3,idx]

marksb  marksc
0      96      64
1      91      14
2      63      27

In [48]:
df.iloc[:3,[1,2]]

marksb  marksc
0      96      64
1      91      14
2      63      27

In [49]:
#sorting

In [52]:
my_data.sort_values(by=["marksa"],ascending=False)

marksa  marksb  marksc
0      93      96      64
4      93      98      14
2      42      63      27
1      12      91      14
3       4      25      93

In [54]:
data_array=my_data.values

In [55]:
print(my_data.shape)

(5, 3)


In [56]:
print(type(data_array))

<class 'numpy.ndarray'>


In [57]:
print(data_array)

[[93 96 64]
 [12 91 14]
 [42 63 27]
 [ 4 25 93]
 [93 98 14]]


In [64]:
newdf=pd.DataFrame(data_array,columns=["a","b","c"])

In [65]:
newdf

a   b   c
0  93  96  64
1  12  91  14
2  42  63  27
3   4  25  93
4  93  98  14